### ISSUE TITLE
Simple case (secret recovery from two random key shares) fails

### ISSUE THREAD

**Issue by ssantos21** [BlockchainCommons/bc-shamir-rust#1]
Why does the code below result in the following error?

```
thread 'main' panicked at src/main.rs:62:52:
called `Result::unwrap()` on an `Err` value: ChecksumFailure
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The line `main.rs:62` refers to `let secret = recover_secret(&indexes, &shares).unwrap();`.

```rust
fn random_keys() {
    let secp = Secp256k1::new();
    let (secret_key01, _public_key01) = secp.generate_keypair(&mut OsRng);
    let (secret_key02, _public_key02) = secp.generate_keypair(&mut OsRng);

    let key01 = secret_key01.secret_bytes().to_vec();
    let key02 = secret_key02.secret_bytes().to_vec();

    let shares = vec![key01, key02];

    let indexes = vec![0, 1];

    let secret = recover_secret(&indexes, &shares).unwrap();

    println!("{}", hex::encode(secret));
}
```

**Comment by wolfmcnally** [comment]
The answer is, "don't do that."

The fact that the error you're getting is `ChecksumFailure` is your first clue that you're doing it wrong. Your second clue is that you're never calling `split_secret()`.

SSS is not designed to "recover" secrets from random shares; it is not a key agreement algorithm: for that you want something like X25519. SSS is designed to shard a secret into shares, then recover that secret from a quorum of those shares.

The original code was designed by a cryptography expert, in C. I converted the code to Rust, but I am not a cryptography expert, and while I carried over the checks that were in the C code, I can't defend this design choice like the expert who originally wrote it. But in my experience, when cryptography experts put in checks like this it is almost always to prevent use of the code in unsafe ways that are known to have major security flaws.

**Comment by ChristopherA** [comment]
If you are looking to safely create a private key based on randomness from more than 2 entities (sources of randomness, CPUs, devices, computers, people, groups) you really want some form of DKG (distributed key generation), as there are many footguns to avoid.

DKG capability is at the bottom of several code stacks, most notable in the MuSig2 and FROST branches of the venerable secp256k1 C++ based stack, or for Rust, use the recently code reviewed DKG for secp256k1 that is part the ZcashFoundations implementation of FROST (https://github.com/ZcashFoundation/frost), and then combine the VSS shares on the machine that you want to use the new private key on instead of using the higher layers of FROST.

Even then, there is some discussion by cryptographers that the DKG for FROST is only provably safe for FROST key generation, and some of the co-author of FROST are looking at instead a more provable form they call STORM https://eprint.iacr.org/2023/292. As far as I know, there is no reviewed implementation of STORM.

But the bottom line is, don't use Shamir Secret Sharing code to combine randomness as a form of private key creation, unless you are a cryptographer AND cryptographic engineer where you really know what you are doing.

**Comment by ChristopherA** [comment]
When you are trying to combine 2 sources of randomness to create a private key, @wolfmcnally is technically correct that you should use something that is closer to a Key Agreement algorithm, such as Diffie-Hellman. Probably safe, but I don't know of any proofs that it is safe beyond its intended purpose for the creation of a shared secret between the two parties. At minimum you'd also have to be sure that the output of your randomness is never written to disk or cache, and is completely erased from memory.

But in general, cryptography is a sharp stick and it’s easy to poke yourself it the eye with it. Be careful.
